In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
df = pd.read_csv("../Resources/charity_data.csv")
df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
df = df.drop(columns=["EIN", "NAME"], axis=0)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   APPLICATION_TYPE        34299 non-null  object
 1   AFFILIATION             34299 non-null  object
 2   CLASSIFICATION          34299 non-null  object
 3   USE_CASE                34299 non-null  object
 4   ORGANIZATION            34299 non-null  object
 5   STATUS                  34299 non-null  int64
 6   INCOME_AMT              34299 non-null  object
 7   SPECIAL_CONSIDERATIONS  34299 non-null  object
 8   ASK_AMT                 34299 non-null  int64
 9   IS_SUCCESSFUL           34299 non-null  int64
dtypes: int64(3), object(7)
memory usage: 2.6+ MB

In [3]:
# Determine the number of unique values in each column.
df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
df.SPECIAL_CONSIDERATIONS.value_counts()

N    34272
Y       27
Name: SPECIAL_CONSIDERATIONS, dtype: int64

In [5]:
df = df.drop(columns=["SPECIAL_CONSIDERATIONS"], axis=1)

In [6]:
df.STATUS.value_counts()

1    34294
0        5
Name: STATUS, dtype: int64

In [7]:
df = df.drop(columns=["STATUS"], axis=1)

In [8]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
bunch = df['APPLICATION_TYPE'].value_counts()
alg_bunch = list(bunch[bunch < 600].index)
mask = df['APPLICATION_TYPE'].isin(alg_bunch)
application_types_to_replace = df.loc[mask, "APPLICATION_TYPE"] = "Other"

# Replace in dataframe
for app in application_types_to_replace:
    df['APPLICATION_TYPE'] = df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
Other      804
T8         737
T7         725
Name: APPLICATION_TYPE, dtype: int64

In [9]:
# You may find it helpful to look at CLASSIFICATION value counts >1
clas = df['CLASSIFICATION'].value_counts()
clas_bunch = list(clas[clas > 1].index)
mask = df['APPLICATION_TYPE'].isin(clas_bunch)
df.loc[mask, "APPLICATION_TYPE"] = "Other"
df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4500        1
C6100        1
C1580        1
C2170        1
C4120        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [10]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
clas = df['CLASSIFICATION'].value_counts()
clas_bunch = list(clas[clas < 1000].index)
mask = df['CLASSIFICATION'].isin(clas_bunch)
classifications_to_replace = df.loc[mask, "CLASSIFICATION"] = "Other"


# Replace in dataframe
for cls in classifications_to_replace:
    df['CLASSIFICATION'] = df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   APPLICATION_TYPE  34299 non-null  object
 1   AFFILIATION       34299 non-null  object
 2   CLASSIFICATION    34299 non-null  object
 3   USE_CASE          34299 non-null  object
 4   ORGANIZATION      34299 non-null  object
 5   INCOME_AMT        34299 non-null  object
 6   ASK_AMT           34299 non-null  int64
 7   IS_SUCCESSFUL     34299 non-null  int64
dtypes: int64(2), object(6)
memory usage: 2.1+ MB

In [12]:
df = pd.get_dummies(df)
df.head()

,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,APPLICATION_TYPE_T8,...,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,5000,1,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,108590,1,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,5000,0,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,6692,1,0,0,1,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
4,142590,1,0,0,1,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0

In [13]:
df["ASK_AMT"].values.reshape(-1, 1)

array([[    5000],
       [  108590],
       [    5000],
       ...,
       [    5000],
       [    5000],
       [36500179]])

In [14]:
scaler = StandardScaler()
df["ASK_AMT"] = scaler.fit_transform(df["ASK_AMT"].values.reshape(-1, 1))
df.head()

,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,APPLICATION_TYPE_T8,...,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,-0.031725,1,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,-0.030536,1,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,-0.031725,0,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,-0.031706,1,0,0,1,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
4,-0.030146,1,0,0,1,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0

In [15]:
df.columns

Index(['ASK_AMT', 'IS_SUCCESSFUL', 'APPLICATION_TYPE_Other',
       'APPLICATION_TYPE_T19', 'APPLICATION_TYPE_T3', 'APPLICATION_TYPE_T4',
       'APPLICATION_TYPE_T5', 'APPLICATION_TYPE_T6', 'APPLICATION_TYPE_T7',
       'APPLICATION_TYPE_T8', 'AFFILIATION_CompanySponsored',
       'AFFILIATION_Family/Parent', 'AFFILIATION_Independent',
       'AFFILIATION_National', 'AFFILIATION_Other', 'AFFILIATION_Regional',
       'CLASSIFICATION_C1000', 'CLASSIFICATION_C1200', 'CLASSIFICATION_C2000',
       'CLASSIFICATION_C2100', 'CLASSIFICATION_C3000', 'CLASSIFICATION_Other',
       'USE_CASE_CommunityServ', 'USE_CASE_Heathcare', 'USE_CASE_Other',
       'USE_CASE_Preservation', 'USE_CASE_ProductDev',
       'ORGANIZATION_Association', 'ORGANIZATION_Co-operative',
       'ORGANIZATION_Corporation', 'ORGANIZATION_Trust', 'INCOME_AMT_0',
       'INCOME_AMT_1-9999', 'INCOME_AMT_10000-24999',
       'INCOME_AMT_100000-499999', 'INCOME_AMT_10M-50M', 'INCOME_AMT_1M-5M',
       'INCOME_AMT_25000-99999', 'INCOME_AMT_50M+', 'INCOME_AMT_5M-10M'],
      dtype='object')

In [16]:
X = df.drop(["IS_SUCCESSFUL"], axis=1).values
y = df["IS_SUCCESSFUL"].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=.25, stratify=y)

print(len(X_train) / len(X))
print(len(X_test) / len(X))

0.7499927111577597
0.25000728884224027

In [17]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [18]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
features = len(X_train[0])
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=5, activation="relu", input_dim=features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=3, activation="relu"))


# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 5)                 200

 dense_1 (Dense)             (None, 3)                 18

 dense_2 (Dense)             (None, 1)                 4

=================================================================
Total params: 222
Trainable params: 222
Non-trainable params: 0
_________________________________________________________________

In [19]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Fit the model to the training data
fit_model = nn.fit(X_train_scaled, y_train, epochs=25)

Epoch 1/25
804/804 [==============================] - 1s 831us/step - loss: 0.6406 - accuracy: 0.6484
Epoch 2/25
804/804 [==============================] - 1s 954us/step - loss: 0.5756 - accuracy: 0.7227
Epoch 3/25
804/804 [==============================] - 1s 834us/step - loss: 0.5679 - accuracy: 0.7262
Epoch 4/25
804/804 [==============================] - 1s 860us/step - loss: 0.5639 - accuracy: 0.7280
Epoch 5/25
804/804 [==============================] - 1s 807us/step - loss: 0.5614 - accuracy: 0.7278
Epoch 6/25
804/804 [==============================] - 1s 798us/step - loss: 0.5594 - accuracy: 0.7278
Epoch 7/25
804/804 [==============================] - 1s 843us/step - loss: 0.5580 - accuracy: 0.7293
Epoch 8/25
804/804 [==============================] - 1s 884us/step - loss: 0.5569 - accuracy: 0.7283
Epoch 9/25
804/804 [==============================] - 1s 1ms/step - loss: 0.5550 - accuracy: 0.7297
Epoch 10/25
804/804 [==============================] - 1s 1ms/step - loss: 0.5542 - accuracy: 0.7295
Epoch 11/25
804/804 [==============================] - 1s 1ms/step - loss: 0.5537 - accuracy: 0.7296
Epoch 12/25
804/804 [==============================] - 1s 973us/step - loss: 0.5533 - accuracy: 0.7299
Epoch 13/25
804/804 [==============================] - 1s 987us/step - loss: 0.5529 - accuracy: 0.7300
Epoch 14/25
804/804 [==============================] - 1s 1ms/step - loss: 0.5524 - accuracy: 0.7301
Epoch 15/25
804/804 [==============================] - 1s 1ms/step - loss: 0.5522 - accuracy: 0.7298
Epoch 16/25
804/804 [==============================] - 1s 929us/step - loss: 0.5521 - accuracy: 0.7302
Epoch 17/25
804/804 [==============================] - 1s 1ms/step - loss: 0.5517 - accuracy: 0.7304
Epoch 18/25
804/804 [==============================] - 1s 1ms/step - loss: 0.5516 - accuracy: 0.7305
Epoch 19/25
804/804 [==============================] - 1s 949us/step - loss: 0.5516 - accuracy: 0.7304
Epoch 20/25
804/804 [==============================] - 1s 891us/step - loss: 0.5514 - accuracy: 0.7304
Epoch 21/25
804/804 [==============================] - 1s 823us/step - loss: 0.5513 - accuracy: 0.7306
Epoch 22/25
804/804 [==============================] - 1s 890us/step - loss: 0.5513 - accuracy: 0.7305
Epoch 23/25
804/804 [==============================] - 1s 1ms/step - loss: 0.5510 - accuracy: 0.7303
Epoch 24/25
804/804 [==============================] - 1s 852us/step - loss: 0.5511 - accuracy: 0.7304
Epoch 25/25
804/804 [==============================] - 1s 1ms/step - loss: 0.5506 - accuracy: 0.7308

In [20]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5588 - accuracy: 0.7202 - 331ms/epoch - 1ms/step
Loss: 0.5588015913963318, Accuracy: 0.7202332615852356

In [30]:
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=8, activation="relu", input_dim=features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=4, activation="relu"))


# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_13 (Dense)            (None, 8)                 320

 dense_14 (Dense)            (None, 4)                 36

 dense_15 (Dense)            (None, 1)                 5

=================================================================
Total params: 361
Trainable params: 361
Non-trainable params: 0
_________________________________________________________________

In [31]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Fit the model to the training data
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 1s 857us/step - loss: 0.6025 - accuracy: 0.6911
Epoch 2/50
804/804 [==============================] - 1s 930us/step - loss: 0.5667 - accuracy: 0.7218
Epoch 3/50
804/804 [==============================] - 1s 943us/step - loss: 0.5606 - accuracy: 0.7269
Epoch 4/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5576 - accuracy: 0.7289
Epoch 5/50
804/804 [==============================] - 1s 992us/step - loss: 0.5558 - accuracy: 0.7285
Epoch 6/50
804/804 [==============================] - 1s 978us/step - loss: 0.5549 - accuracy: 0.7282
Epoch 7/50
804/804 [==============================] - 1s 926us/step - loss: 0.5541 - accuracy: 0.7285
Epoch 8/50
804/804 [==============================] - 1s 858us/step - loss: 0.5535 - accuracy: 0.7289
Epoch 9/50
804/804 [==============================] - 1s 831us/step - loss: 0.5527 - accuracy: 0.7294
Epoch 10/50
804/804 [==============================] - 1s 836us/step - loss: 0.5526 - accuracy: 0.7301
Epoch 11/50
804/804 [==============================] - 1s 839us/step - loss: 0.5521 - accuracy: 0.7314
Epoch 12/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5517 - accuracy: 0.7324
Epoch 13/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5513 - accuracy: 0.7325
Epoch 14/50
804/804 [==============================] - 1s 935us/step - loss: 0.5510 - accuracy: 0.7324
Epoch 15/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5508 - accuracy: 0.7329
Epoch 16/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5508 - accuracy: 0.7326
Epoch 17/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5505 - accuracy: 0.7329
Epoch 18/50
804/804 [==============================] - 1s 886us/step - loss: 0.5505 - accuracy: 0.7319
Epoch 19/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5503 - accuracy: 0.7332
Epoch 20/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5501 - accuracy: 0.7328
Epoch 21/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5499 - accuracy: 0.7328
Epoch 22/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5496 - accuracy: 0.7341
Epoch 23/50
804/804 [==============================] - 1s 982us/step - loss: 0.5498 - accuracy: 0.7332
Epoch 24/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5493 - accuracy: 0.7341
Epoch 25/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5495 - accuracy: 0.7330
Epoch 26/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5492 - accuracy: 0.7344
Epoch 27/50
804/804 [==============================] - 1s 925us/step - loss: 0.5492 - accuracy: 0.7346
Epoch 28/50
804/804 [==============================] - 1s 963us/step - loss: 0.5489 - accuracy: 0.7340
Epoch 29/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5490 - accuracy: 0.7341
Epoch 30/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5489 - accuracy: 0.7341
Epoch 31/50
804/804 [==============================] - 1s 944us/step - loss: 0.5491 - accuracy: 0.7336
Epoch 32/50
804/804 [==============================] - 1s 875us/step - loss: 0.5489 - accuracy: 0.7343
Epoch 33/50
804/804 [==============================] - 1s 935us/step - loss: 0.5484 - accuracy: 0.7347
Epoch 34/50
804/804 [==============================] - 1s 841us/step - loss: 0.5481 - accuracy: 0.7350
Epoch 35/50
804/804 [==============================] - 1s 845us/step - loss: 0.5481 - accuracy: 0.7349
Epoch 36/50
804/804 [==============================] - 1s 857us/step - loss: 0.5481 - accuracy: 0.7348
Epoch 37/50
804/804 [==============================] - 1s 881us/step - loss: 0.5479 - accuracy: 0.7350
Epoch 38/50
804/804 [==============================] - 1s 899us/step - loss: 0.5479 - accuracy: 0.7346
Epoch 39/50
804/804 [==============================] - 1s 851us/step - loss: 0.5477 - accuracy: 0.7348
Epoch 40/50
804/804 [==============================] - 1s 839us/step - loss: 0.5475 - accuracy: 0.7350
Epoch 41/50
804/804 [==============================] - 1s 815us/step - loss: 0.5476 - accuracy: 0.7348
Epoch 42/50
804/804 [==============================] - 1s 824us/step - loss: 0.5476 - accuracy: 0.7353
Epoch 43/50
804/804 [==============================] - 1s 841us/step - loss: 0.5470 - accuracy: 0.7352
Epoch 44/50
804/804 [==============================] - 1s 846us/step - loss: 0.5472 - accuracy: 0.7351
Epoch 45/50
804/804 [==============================] - 1s 843us/step - loss: 0.5471 - accuracy: 0.7355
Epoch 46/50
804/804 [==============================] - 1s 835us/step - loss: 0.5473 - accuracy: 0.7358
Epoch 47/50
804/804 [==============================] - 1s 863us/step - loss: 0.5471 - accuracy: 0.7358
Epoch 48/50
804/804 [==============================] - 1s 906us/step - loss: 0.5467 - accuracy: 0.7350
Epoch 49/50
804/804 [==============================] - 1s 839us/step - loss: 0.5469 - accuracy: 0.7353
Epoch 50/50
804/804 [==============================] - 1s 899us/step - loss: 0.5467 - accuracy: 0.7358

In [32]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5571 - accuracy: 0.7236 - 355ms/epoch - 1ms/step
Loss: 0.5571443438529968, Accuracy: 0.7236151695251465

In [24]:
# Train the model
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
features = len(X_train[0])
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=9, activation="relu", input_dim=features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=5, activation="relu"))


# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 9)                 360

 dense_7 (Dense)             (None, 5)                 50

 dense_8 (Dense)             (None, 1)                 6

=================================================================
Total params: 416
Trainable params: 416
Non-trainable params: 0
_________________________________________________________________

In [25]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Fit the model to the training data
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 1ms/step - loss: 0.6024 - accuracy: 0.6992
Epoch 2/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5619 - accuracy: 0.7255
Epoch 3/100
804/804 [==============================] - 1s 850us/step - loss: 0.5566 - accuracy: 0.7275
Epoch 4/100
804/804 [==============================] - 1s 884us/step - loss: 0.5550 - accuracy: 0.7292
Epoch 5/100
804/804 [==============================] - 1s 904us/step - loss: 0.5540 - accuracy: 0.7295
Epoch 6/100
804/804 [==============================] - 1s 840us/step - loss: 0.5526 - accuracy: 0.7303
Epoch 7/100
804/804 [==============================] - 1s 852us/step - loss: 0.5521 - accuracy: 0.7304
Epoch 8/100
804/804 [==============================] - 1s 837us/step - loss: 0.5513 - accuracy: 0.7310
Epoch 9/100
804/804 [==============================] - 1s 846us/step - loss: 0.5510 - accuracy: 0.7314
Epoch 10/100
804/804 [==============================] - 1s 866us/step - loss: 0.5510 - accuracy: 0.7322
Epoch 11/100
804/804 [==============================] - 1s 830us/step - loss: 0.5505 - accuracy: 0.7318
Epoch 12/100
804/804 [==============================] - 1s 903us/step - loss: 0.5503 - accuracy: 0.7317
Epoch 13/100
804/804 [==============================] - 1s 829us/step - loss: 0.5502 - accuracy: 0.7318
Epoch 14/100
804/804 [==============================] - 1s 823us/step - loss: 0.5499 - accuracy: 0.7315
Epoch 15/100
804/804 [==============================] - 1s 830us/step - loss: 0.5495 - accuracy: 0.7312
Epoch 16/100
804/804 [==============================] - 1s 876us/step - loss: 0.5491 - accuracy: 0.7324
Epoch 17/100
804/804 [==============================] - 1s 875us/step - loss: 0.5493 - accuracy: 0.7321
Epoch 18/100
804/804 [==============================] - 1s 995us/step - loss: 0.5490 - accuracy: 0.7327
Epoch 19/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5487 - accuracy: 0.7323
Epoch 20/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5485 - accuracy: 0.7326
Epoch 21/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5485 - accuracy: 0.7318
Epoch 22/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5483 - accuracy: 0.7338
Epoch 23/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5481 - accuracy: 0.7325
Epoch 24/100
804/804 [==============================] - 1s 935us/step - loss: 0.5481 - accuracy: 0.7334
Epoch 25/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5480 - accuracy: 0.7333
Epoch 26/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5476 - accuracy: 0.7335
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5476 - accuracy: 0.7328
Epoch 28/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5475 - accuracy: 0.7332
Epoch 29/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5473 - accuracy: 0.7328
Epoch 30/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5472 - accuracy: 0.7331
Epoch 31/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5474 - accuracy: 0.7318
Epoch 32/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5469 - accuracy: 0.7332
Epoch 33/100
804/804 [==============================] - 1s 915us/step - loss: 0.5470 - accuracy: 0.7337
Epoch 34/100
804/804 [==============================] - 1s 834us/step - loss: 0.5469 - accuracy: 0.7329
Epoch 35/100
804/804 [==============================] - 1s 845us/step - loss: 0.5467 - accuracy: 0.7324
Epoch 36/100
804/804 [==============================] - 1s 904us/step - loss: 0.5466 - accuracy: 0.7320
Epoch 37/100
804/804 [==============================] - 1s 854us/step - loss: 0.5465 - accuracy: 0.7338
Epoch 38/100
804/804 [==============================] - 1s 844us/step - loss: 0.5465 - accuracy: 0.7332
Epoch 39/100
804/804 [==============================] - 1s 908us/step - loss: 0.5465 - accuracy: 0.7330
Epoch 40/100
804/804 [==============================] - 1s 840us/step - loss: 0.5461 - accuracy: 0.7339
Epoch 41/100
804/804 [==============================] - 1s 828us/step - loss: 0.5459 - accuracy: 0.7338
Epoch 42/100
804/804 [==============================] - 1s 834us/step - loss: 0.5461 - accuracy: 0.7332
Epoch 43/100
804/804 [==============================] - 1s 865us/step - loss: 0.5458 - accuracy: 0.7345
Epoch 44/100
804/804 [==============================] - 1s 867us/step - loss: 0.5457 - accuracy: 0.7345
Epoch 45/100
804/804 [==============================] - 1s 820us/step - loss: 0.5460 - accuracy: 0.7346
Epoch 46/100
804/804 [==============================] - 1s 820us/step - loss: 0.5459 - accuracy: 0.7342
Epoch 47/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5458 - accuracy: 0.7343
Epoch 48/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5455 - accuracy: 0.7343
Epoch 49/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5457 - accuracy: 0.7345
Epoch 50/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5457 - accuracy: 0.7338
Epoch 51/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5455 - accuracy: 0.7345
Epoch 52/100
804/804 [==============================] - 1s 865us/step - loss: 0.5455 - accuracy: 0.7342
Epoch 53/100
804/804 [==============================] - 1s 881us/step - loss: 0.5454 - accuracy: 0.7339
Epoch 54/100
804/804 [==============================] - 1s 857us/step - loss: 0.5454 - accuracy: 0.7351
Epoch 55/100
804/804 [==============================] - 1s 833us/step - loss: 0.5456 - accuracy: 0.7346
Epoch 56/100
804/804 [==============================] - 1s 856us/step - loss: 0.5454 - accuracy: 0.7342
Epoch 57/100
804/804 [==============================] - 1s 888us/step - loss: 0.5454 - accuracy: 0.7348
Epoch 58/100
804/804 [==============================] - 1s 860us/step - loss: 0.5452 - accuracy: 0.7344
Epoch 59/100
804/804 [==============================] - 1s 911us/step - loss: 0.5452 - accuracy: 0.7347
Epoch 60/100
804/804 [==============================] - 1s 866us/step - loss: 0.5452 - accuracy: 0.7336
Epoch 61/100
804/804 [==============================] - 1s 867us/step - loss: 0.5451 - accuracy: 0.7350
Epoch 62/100
804/804 [==============================] - 1s 890us/step - loss: 0.5454 - accuracy: 0.7346
Epoch 63/100
804/804 [==============================] - 1s 913us/step - loss: 0.5452 - accuracy: 0.7339
Epoch 64/100
804/804 [==============================] - 1s 921us/step - loss: 0.5452 - accuracy: 0.7348
Epoch 65/100
804/804 [==============================] - 1s 875us/step - loss: 0.5449 - accuracy: 0.7345
Epoch 66/100
804/804 [==============================] - 1s 890us/step - loss: 0.5451 - accuracy: 0.7351
Epoch 67/100
804/804 [==============================] - 1s 868us/step - loss: 0.5449 - accuracy: 0.7340
Epoch 68/100
804/804 [==============================] - 1s 889us/step - loss: 0.5448 - accuracy: 0.7344
Epoch 69/100
804/804 [==============================] - 1s 849us/step - loss: 0.5450 - accuracy: 0.7350
Epoch 70/100
804/804 [==============================] - 1s 908us/step - loss: 0.5450 - accuracy: 0.7338
Epoch 71/100
804/804 [==============================] - 1s 852us/step - loss: 0.5446 - accuracy: 0.7357
Epoch 72/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5447 - accuracy: 0.7348
Epoch 73/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5449 - accuracy: 0.7352
Epoch 74/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5448 - accuracy: 0.7357
Epoch 75/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5449 - accuracy: 0.7348
Epoch 76/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5446 - accuracy: 0.7345
Epoch 77/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5446 - accuracy: 0.7354
Epoch 78/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5445 - accuracy: 0.7352
Epoch 79/100
804/804 [==============================] - 1s 872us/step - loss: 0.5447 - accuracy: 0.7355
Epoch 80/100

804/804 [==============================] - 1s 959us/step - loss: 0.5446 - accuracy: 0.7350
Epoch 81/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5447 - accuracy: 0.7346
Epoch 82/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5445 - accuracy: 0.7352
Epoch 83/100
804/804 [==============================] - 1s 849us/step - loss: 0.5445 - accuracy: 0.7356
Epoch 84/100
804/804 [==============================] - 1s 829us/step - loss: 0.5445 - accuracy: 0.7344
Epoch 85/100
804/804 [==============================] - 1s 825us/step - loss: 0.5444 - accuracy: 0.7349
Epoch 86/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5444 - accuracy: 0.7347
Epoch 87/100
804/804 [==============================] - 1s 968us/step - loss: 0.5445 - accuracy: 0.7358
Epoch 88/100
804/804 [==============================] - 1s 958us/step - loss: 0.5446 - accuracy: 0.7364
Epoch 89/100
804/804 [==============================] - 1s 850us/step - loss: 0.5442 - accuracy: 0.7352
Epoch 90/100
804/804 [==============================] - 1s 918us/step - loss: 0.5443 - accuracy: 0.7348
Epoch 91/100
804/804 [==============================] - 1s 937us/step - loss: 0.5446 - accuracy: 0.7354
Epoch 92/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5442 - accuracy: 0.7348
Epoch 93/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5443 - accuracy: 0.7348
Epoch 94/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5444 - accuracy: 0.7357
Epoch 95/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5442 - accuracy: 0.7360
Epoch 96/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5440 - accuracy: 0.7354
Epoch 97/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7350
Epoch 98/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5443 - accuracy: 0.7357
Epoch 99/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5443 - accuracy: 0.7347
Epoch 100/100
804/804 [==============================] - 1s 910us/step - loss: 0.5442 - accuracy: 0.7350

In [26]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5562 - accuracy: 0.7237 - 251ms/epoch - 937us/step
Loss: 0.5561891198158264, Accuracy: 0.7237317562103271

In [27]:
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=8, activation="relu", input_dim=features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=6, activation="relu"))

nn.add(tf.keras.layers.Dense(units=4, activation="relu"))
# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_9 (Dense)             (None, 8)                 320

 dense_10 (Dense)            (None, 6)                 54

 dense_11 (Dense)            (None, 4)                 28

 dense_12 (Dense)            (None, 1)                 5

=================================================================
Total params: 407
Trainable params: 407
Non-trainable params: 0
_________________________________________________________________

In [28]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Fit the model to the training data
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6499 - accuracy: 0.6654
Epoch 2/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5853 - accuracy: 0.7201
Epoch 3/50
804/804 [==============================] - 1s 945us/step - loss: 0.5709 - accuracy: 0.7252
Epoch 4/50
804/804 [==============================] - 1s 932us/step - loss: 0.5651 - accuracy: 0.7276
Epoch 5/50
804/804 [==============================] - 1s 911us/step - loss: 0.5623 - accuracy: 0.7278
Epoch 6/50
804/804 [==============================] - 1s 895us/step - loss: 0.5598 - accuracy: 0.7280
Epoch 7/50
804/804 [==============================] - 1s 901us/step - loss: 0.5583 - accuracy: 0.7292
Epoch 8/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5566 - accuracy: 0.7283
Epoch 9/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5552 - accuracy: 0.7283
Epoch 10/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5542 - accuracy: 0.7302
Epoch 11/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5535 - accuracy: 0.7314
Epoch 12/50
804/804 [==============================] - 1s 885us/step - loss: 0.5527 - accuracy: 0.7306
Epoch 13/50
804/804 [==============================] - 1s 864us/step - loss: 0.5523 - accuracy: 0.7322
Epoch 14/50
804/804 [==============================] - 1s 867us/step - loss: 0.5514 - accuracy: 0.7338
Epoch 15/50
804/804 [==============================] - 1s 865us/step - loss: 0.5510 - accuracy: 0.7331
Epoch 16/50
804/804 [==============================] - 1s 855us/step - loss: 0.5507 - accuracy: 0.7330
Epoch 17/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5507 - accuracy: 0.7344
Epoch 18/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5502 - accuracy: 0.7334
Epoch 19/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5501 - accuracy: 0.7350
Epoch 20/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5502 - accuracy: 0.7340
Epoch 21/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5494 - accuracy: 0.7335
Epoch 22/50
804/804 [==============================] - 1s 919us/step - loss: 0.5495 - accuracy: 0.7345
Epoch 23/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5492 - accuracy: 0.7350
Epoch 24/50
804/804 [==============================] - 1s 977us/step - loss: 0.5490 - accuracy: 0.7353
Epoch 25/50
804/804 [==============================] - 1s 962us/step - loss: 0.5488 - accuracy: 0.7355
Epoch 26/50
804/804 [==============================] - 1s 957us/step - loss: 0.5484 - accuracy: 0.7354
Epoch 27/50
804/804 [==============================] - 1s 911us/step - loss: 0.5485 - accuracy: 0.7342
Epoch 28/50
804/804 [==============================] - 1s 941us/step - loss: 0.5477 - accuracy: 0.7342
Epoch 29/50
804/804 [==============================] - 1s 869us/step - loss: 0.5478 - accuracy: 0.7344
Epoch 30/50
804/804 [==============================] - 1s 871us/step - loss: 0.5476 - accuracy: 0.7358
Epoch 31/50
804/804 [==============================] - 1s 957us/step - loss: 0.5477 - accuracy: 0.7350
Epoch 32/50
804/804 [==============================] - 1s 960us/step - loss: 0.5475 - accuracy: 0.7344
Epoch 33/50
804/804 [==============================] - 1s 965us/step - loss: 0.5473 - accuracy: 0.7354
Epoch 34/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5470 - accuracy: 0.7360
Epoch 35/50
804/804 [==============================] - 1s 964us/step - loss: 0.5466 - accuracy: 0.7364
Epoch 36/50
804/804 [==============================] - 1s 951us/step - loss: 0.5467 - accuracy: 0.7358
Epoch 37/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5468 - accuracy: 0.7357
Epoch 38/50
804/804 [==============================] - 1s 875us/step - loss: 0.5468 - accuracy: 0.7363
Epoch 39/50
804/804 [==============================] - 1s 891us/step - loss: 0.5465 - accuracy: 0.7362
Epoch 40/50
804/804 [==============================] - 1s 858us/step - loss: 0.5461 - accuracy: 0.7353
Epoch 41/50
804/804 [==============================] - 1s 923us/step - loss: 0.5462 - accuracy: 0.7357
Epoch 42/50
804/804 [==============================] - 1s 897us/step - loss: 0.5462 - accuracy: 0.7358
Epoch 43/50
804/804 [==============================] - 1s 937us/step - loss: 0.5460 - accuracy: 0.7360
Epoch 44/50
804/804 [==============================] - 1s 947us/step - loss: 0.5463 - accuracy: 0.7362
Epoch 45/50
804/804 [==============================] - 1s 920us/step - loss: 0.5454 - accuracy: 0.7378
Epoch 46/50
804/804 [==============================] - 1s 918us/step - loss: 0.5460 - accuracy: 0.7358
Epoch 47/50
804/804 [==============================] - 1s 899us/step - loss: 0.5462 - accuracy: 0.7360
Epoch 48/50
804/804 [==============================] - 1s 931us/step - loss: 0.5457 - accuracy: 0.7365
Epoch 49/50
804/804 [==============================] - 1s 906us/step - loss: 0.5457 - accuracy: 0.7358
Epoch 50/50
804/804 [==============================] - 1s 930us/step - loss: 0.5460 - accuracy: 0.7357

In [29]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5577 - accuracy: 0.7250 - 254ms/epoch - 949us/step
Loss: 0.5577083230018616, Accuracy: 0.7250145673751831